FIND_PATH(DEVIL_INCLUDE_DIR NAMES IL/il.h)
MARK_AS_ADVANCED(DEVIL_INCLUDE_DIR)
 
FIND_LIBRARY(DEVIL_LIBRARY NAMES
IL
libIL
)
MARK_AS_ADVANCED(DEVIL_LIBRARY)
 
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Devil DEFAULT_MSG DEVIL_LIBRARY DEVIL_INCLUDE_DIR)
